language: python
python: 3.5
addons:
  apt:
    packages:
    - libboost-dev
    - libhdf5-dev
install:
  - git clone https://github.com/pybind/pybind11.git
  - python pybind11/setup.py install_headers
script:
  - cmake src
  - make -j4 -l4
