language: python
python: 3.5
addons:
  apt:
    packages:
    - libboost-dev
    - libhdf5-dev
install:
  - pip install pybind11
script:
  - which python
  - dpkg -L python3-all-dev
  - dpkg -L python3-dev
  - ls /usr/include/python3.5m
  - ls /usr/local/include/python3.5
  - cmake src
  - make -j4 -l4
sudo: true
