language: python
python: 3.5
addons:
  apt:
    packages:
    - libboost-dev
    - libhdf5-dev
    - python3-all-dev
install:
  - wget -q http://mirrors.kernel.org/ubuntu/pool/universe/p/pybind11/pybind11-dev_2.0.1-4_all.deb
  - sudo dpkg -x *.deb /
script:
  - which python
  - dpkg -L python3-all-dev
  - dpkg -L python3-dev
  - ls /usr/include/python3.5m
  - ls /usr/local/include/python3.5
  - cmake src
  - make -j4 -l4
sudo: true
