language: python
python: 3.5
addons:
  apt:
    packages:
    - libboost-dev
    - libhdf5-dev
install:
  - git clone https://github.com/pybind/pybind11.git
  - cd pybind11; sudo /home/travis/virtualenv/python3.5.5/bin/python setup.py install_headers
script:
  - cmake src
  - make -j4 -l4
